TESTS: Make whitespace_test pass without whitespace
Make whitespace_test pass if no trailing whitespace was detected at all.
Add two comments explaining how searching and failure handling works.

Fixes:
https://fedorahosted.org/sssd/ticket/2816

Reviewed-by: Lukáš Slebodník <lslebodn@redhat.com>

diff --git a/src/tests/whitespace_test b/src/tests/whitespace_test
--- a/src/tests/whitespace_test
+++ b/src/tests/whitespace_test
@@ -14,7 +14,12 @@ if [ ! -d "$GIT_DIR" ]; then
     exit 77
 fi
 
-git grep -n -I '\s\+$' -- "$(git rev-parse --show-toplevel)" |
+{
+    # Look for lines with trailing whitespace in all files tracked by Git
+    git grep -n -I '\s\+$' -- "$(git rev-parse --show-toplevel)" ||
+        # Don't fail if no such lines were found anywhere
+        [[ $? == 1 ]]
+} |
     awk -- "
         BEGIN {
             found = 0
