TESTS: Check new line at end of file
Reviewed-by: Nikolai Kondrashov <Nikolai.Kondrashov@redhat.com>

diff --git a/src/tests/whitespace_test b/src/tests/whitespace_test
--- a/src/tests/whitespace_test
+++ b/src/tests/whitespace_test
@@ -35,3 +35,16 @@ fi
             exit found
         }
     "
+
+declare found_file=false
+while read file; do
+    [[ $file == "src/config/testconfigs/noparse.api.conf" ]] && continue
+    [[ $file =~ ^src/tests/cmocka/p11_nssdb/.*db ]] && continue
+    test `tail -c 1 $ABS_TOP_SRCDIR/$file` && \
+        echo "Missing new line at the eof: $file" && \
+        found_file=true
+done < <(git ls-files)
+
+if $found_file; then
+    exit 1
+fi
